### ISSUE TITLE
whilelist mode allow users not in the list 

### ISSUE THREAD

**Issue by rubinhozzz** [san4op/roundcube_login_control#2]
Using the mode = 'blacklist' works OK, but using 'whitelist' is still not working. I'm trying to log in as "ruben" and "jos" which are not in the whitelist. The only user in the whitelist is "herman", however i can still log in as "ruben" and "jos". Is it my config well set up? 
```
<?php
##
## Login Control configuration file
##

// List mode: 'whitelist' or 'blacklist'
$config['login_control_mode'] = 'whitelist';

// List of IPV4 addresses
// Format:
//   array(
//     'username' => 'IPV4 or NETWORK',
//     'username' => array(
//       'IPV4 or NETWORK',
//       'IPV4 or NETWORK',
//       ...
//     ),
//     ...
//   )
$config['login_control_list'] = array(
    'herman' => array('0.0.0.0/0')
);

?>
```
Thanks in advance

**Comment by san4op** [comment]
this is not bug. whitelist works as: for every usernames in login_control_list login allowed only from listed networks, for others login allowed always. i add what you want in new version.

**Comment by san4op** [comment]
small [patch](https://github.com/san4op/roundcube_login_control/files/2089140/login_control.patch.zip) and configuration for your want:
```php
<?php
$config['login_control_mode'] = 'whitelist';
$config['login_control_list'] = array(
    '*' => '255.255.255.255', /* block all logins */
    'username' => '0.0.0.0/0', /* required if use $config['username_domain'] */
    'username@domain.com' => '0.0.0.0/0',
);
?>
```

**Comment by rubinhozzz** [comment]
Thanks a lot for the patch. It works like a charm.
